# Bybit UNIFIED Account Configuration for Testnet
# Конфигурация для Bybit Testnet с UNIFIED аккаунтом

# Database Configuration  
database:
  host: localhost
  port: 5433
  database: fox_crypto
  user: elcrypto
  password: ${DB_PASSWORD}
  pool_size: 10
  max_overflow: 20

# Exchange Configuration
exchanges:
  binance:
    enabled: false  # Отключаем Binance для тестирования Bybit
    testnet: true
    api_key: ${BINANCE_TESTNET_API_KEY}
    api_secret: ${BINANCE_TESTNET_SECRET}
    
  bybit:
    enabled: true
    testnet: true  # ВАЖНО: используем testnet
    api_key: ${BYBIT_API_KEY}
    api_secret: ${BYBIT_API_SECRET}
    
    # ВАЖНО: Настройки для UNIFIED account
    options:
      defaultType: 'future'      # Тип торговли: 'spot' или 'future'
      accountType: 'UNIFIED'     # ОБЯЗАТЕЛЬНО для v5 API
      recvWindow: 60000
      enableRateLimit: true
      adjustForTimeDifference: true
    
    # URLs для testnet (будут установлены автоматически в коде)
    # Здесь для документации
    testnet_urls:
      rest: 'https://api-testnet.bybit.com'
      websocket_public: 'wss://stream-testnet.bybit.com/v5/public'
      websocket_private: 'wss://stream-testnet.bybit.com/v5/private'
    
    # Настройки подключения
    ws_reconnect_delay: 5
    ws_reconnect_delay_max: 60
    ws_max_reconnect_attempts: -1  # Бесконечные попытки
    ws_heartbeat_interval: 30
    ws_heartbeat_timeout: 60

# Trading Configuration
trading:
  mode: shadow  # production, shadow, backtest
  enabled_pairs:
    - BTC/USDT:USDT
    - ETH/USDT:USDT
  
  # Position Management
  max_positions: 3
  position_size_pct: 10.0  # % от баланса
  max_position_size: 1000  # USDT
  min_position_size: 10    # USDT
  leverage: 1              # Для начала без плеча
  
  # Order Settings
  order_type: limit
  time_in_force: GTC
  reduce_only: false
  post_only: false

# Risk Management
risk_management:
  enabled: true
  max_daily_loss: 100      # USDT
  max_open_positions: 3
  max_exposure_pct: 30.0   # % от баланса
  max_single_loss: 50      # USDT
  
  # Stop Loss Settings
  stop_loss:
    enabled: true
    type: fixed            # fixed, trailing, combined
    fixed_percentage: 2.0
    
  # Take Profit Settings
  take_profit:
    enabled: true
    target_percentage: 3.0
    partial_targets:
      - percent: 50        # Закрыть 50% позиции
        target: 1.5        # При 1.5% профита
      - percent: 100       # Закрыть остаток
        target: 3.0        # При 3% профита

# Signal Processing (отключено для тестирования подключения)
signals:
  enabled: false
  min_score_week: 70
  min_score_month: 80
  time_window_minutes: 5
  max_signals_per_hour: 10

# Monitoring
monitoring:
  enabled: true
  health_check_interval: 60
  performance_interval: 300

# Logging
logging:
  level: INFO
  file: logs/trading_bot_bybit.log
  max_size: 10485760
  backup_count: 5

# System
system:
  shutdown_timeout: 10     # Секунды
  timezone: UTC