exchanges:
  binance:
    rate_limit: true
    ws_heartbeat_interval: 30
    ws_timeout: 60
    ws_reconnect_delay: 5
    ws_max_reconnect_attempts: 10

    # Exchange specific settings
    futures_type: "USDT-M"  # USDT-M or COIN-M
    margin_type: "CROSS"     # CROSS or ISOLATED

    # Order settings
    post_only: false
    time_in_force: "GTC"

  bybit:
    rate_limit: true
    ws_heartbeat_interval: 20
    ws_timeout: 60
    ws_reconnect_delay: 5
    ws_max_reconnect_attempts: 10

    # Exchange specific
    category: "linear"
    settle_coin: "USDT"