strategies:
  # Production settings - strict limits for real money
  production:
    # Position sizing
    position_size_usd: 100
    max_positions: 100
    max_exposure_usd: 10000

    # Risk management
    stop_loss_percent: 2.0
    take_profit_percent: 3.0

    # Trailing stop
    trailing_activation_percent: 1.5
    trailing_callback_percent: 0.5
    use_breakeven: true
    breakeven_at_percent: 0.5

    # Signal filtering
    min_score_week: 70  # Higher threshold for production
    min_score_month: 80
    signal_time_window_minutes: 10
    max_trades_per_15min: 10  # Conservative for production

    # Execution - strict limits
    max_slippage_percent: 0.5
    max_spread_percent: 0.5
  
  # Testnet settings - relaxed limits for testing
  testnet:
    # Position sizing
    position_size_usd: 100
    max_positions: 100
    max_exposure_usd: 10000

    # Risk management
    stop_loss_percent: 2.0
    take_profit_percent: 3.0

    # Trailing stop
    trailing_activation_percent: 1.5
    trailing_callback_percent: 0.5
    use_breakeven: true
    breakeven_at_percent: 0.5

    # Signal filtering
    min_score_week: 50  # Lower threshold for testing
    min_score_month: 50
    signal_time_window_minutes: 10
    max_trades_per_15min: 20  # More signals for testing

    # Execution - high tolerance for poor testnet liquidity
    max_slippage_percent: 50.0  # High tolerance for testnet
    max_spread_percent: 50.0    # High tolerance for testnet
  
  # Default strategy (fallback)
  default:
    # Position sizing
    position_size_usd: 100
    max_positions: 100
    max_exposure_usd: 10000

    # Risk management
    stop_loss_percent: 2.0
    take_profit_percent: 3.0

    # Trailing stop
    trailing_activation_percent: 1.5
    trailing_callback_percent: 0.5
    use_breakeven: true
    breakeven_at_percent: 0.5

    # Signal filtering
    min_score_week: 50
    min_score_month: 50
    signal_time_window_minutes: 10
    max_trades_per_15min: 20

    # Execution
    max_slippage_percent: 0.5
    max_spread_percent: 0.5

  aggressive:
    position_size_usd: 200
    max_positions: 15
    stop_loss_percent: 3.0
    trailing_activation_percent: 1.0

  conservative:
    position_size_usd: 50
    max_positions: 5
    stop_loss_percent: 1.5
    min_score_week: 80
    min_score_month: 85