#!/bin/bash
# Setup SSH tunnel for PostgreSQL connection

echo "Setting up SSH tunnel to production database..."
echo "This script will create an SSH tunnel to forward local port 15432 to remote PostgreSQL"
echo ""
echo "Usage: ssh -L 15432:localhost:5432 user@10.8.0.1"
echo ""
echo "Please run one of these commands in a separate terminal:"
echo ""
echo "Option 1 - Direct SSH tunnel:"
echo "ssh -N -L 15432:10.8.0.1:5432 your_ssh_user@your_jump_host"
echo ""
echo "Option 2 - If PostgreSQL is on the same server as SSH:"
echo "ssh -N -L 15432:localhost:5432 your_ssh_user@10.8.0.1"
echo ""
echo "After establishing the tunnel, update .env file:"
echo "DB_HOST=localhost"
echo "DB_PORT=15432"
echo ""
echo "Note: Keep the SSH tunnel running while using the trading bot"